package org.chromium.webapk.a62461adf62f597a7_v2;

/* This class is generated by JADX */
public final class R {

    public static final class bool {
        public static final int is_splash_icon_maskable = 2130771968;
        public static final int opaque_main_activity_enabled_default = 2130771969;
        public static final int transparent_main_activity_enabled_default = 2130771970;
    }

    public static final class color {
        public static final int background_color_non_empty = 2130837504;
        public static final int webapk_black_alpha_38 = 2130837505;
        public static final int webapk_black_alpha_54 = 2130837506;
        public static final int webapk_black_alpha_87 = 2130837507;
        public static final int webapp_default_bg = 2130837508;
        public static final int webapp_grey_900 = 2130837509;
        public static final int webapp_splash_title_light = 2130837510;
        public static final int white_adaptive_ic_launcher_background = 2130837511;
    }

    public static final class dimen {
        public static final int dialog_content_padding = 2130903040;
        public static final int dialog_content_top_padding = 2130903041;
        public static final int headline_size_medium = 2130903042;
        public static final int list_column_padding = 2130903043;
        public static final int oom_splash_icon_size = 2130903044;
        public static final int title_bottom_padding = 2130903045;
        public static final int webapk_text_size_large = 2130903046;
        public static final int webapk_text_size_medium_dense = 2130903047;
        public static final int webapp_splash_image_size_ideal = 2130903048;
        public static final int webapp_splash_image_size_minimum = 2130903049;
        public static final int webapp_splash_large_title_margin_bottom = 2130903050;
        public static final int webapp_splash_offset = 2130903051;
    }

    public static final class drawable {
        public static final int ic_site_settings = 2130968576;
        public static final int last_resort_runtime_host_logo = 2130968577;
        public static final int notification_badge = 2130968578;
        public static final int shortcut_1_icon = 2130968579;
        public static final int shortcut_2_icon = 2130968580;
        public static final int shortcut_3_icon = 2130968581;
        public static final int shortcut_4_icon = 2130968582;
        public static final int splash_icon = 2130968583;
    }

    public static final class id {
        public static final int browser_icon = 2131034112;
        public static final int browser_list = 2131034113;
        public static final int browser_name = 2131034114;
        public static final int desc = 2131034115;
        public static final int splashscreen_icon_view = 2131034116;
        public static final int webapp_splash_screen_icon = 2131034117;
        public static final int webapp_splash_screen_layout = 2131034118;
        public static final int webapp_splash_screen_name = 2131034119;
        public static final int webapp_splash_space = 2131034120;
    }

    public static final class layout {
        public static final int choose_host_browser_dialog = 2131099648;
        public static final int host_browser_list_item = 2131099649;
        public static final int splash_screen_view = 2131099650;
        public static final int webapp_splash_screen_large = 2131099651;
        public static final int webapp_splash_screen_no_icon = 2131099652;
    }

    public static final class mipmap {
        public static final int app_icon = 2131165184;
        public static final int app_icon_hdpi = 2131165185;
        public static final int app_icon_mdpi = 2131165186;
        public static final int app_icon_xhdpi = 2131165187;
        public static final int app_icon_xxhdpi = 2131165188;
        public static final int app_icon_xxxhdpi = 2131165189;
        public static final int ic_launcher = 2131165190;
        public static final int ic_launcher_background = 2131165191;
        public static final int ic_launcher_foreground = 2131165192;
        public static final int maskable_app_icon = 2131165193;
        public static final int maskable_app_icon_hdpi = 2131165194;
        public static final int maskable_app_icon_mdpi = 2131165195;
        public static final int maskable_app_icon_xhdpi = 2131165196;
        public static final int maskable_app_icon_xxhdpi = 2131165197;
        public static final int maskable_app_icon_xxxhdpi = 2131165198;
        public static final int maskable_splash_icon_xxhdpi = 2131165199;
        public static final int maskable_splash_icon_xxxhdpi = 2131165200;
        public static final int splash_icon_xxhdpi = 2131165201;
        public static final int splash_icon_xxxhdpi = 2131165202;
    }

    public static final class string {
        public static final int choose_host_browser = 2131230720;
        public static final int choose_host_browser_dialog_quit = 2131230721;
        public static final int choose_host_browser_dialog_title = 2131230722;
        public static final int host_browser_item_not_supporting_webapks = 2131230723;
        public static final int install_host_browser_dialog_install_button = 2131230724;
        public static final int install_host_browser_dialog_title = 2131230725;
        public static final int name = 2131230726;
        public static final int no_support_for_launch_settings = 2131230727;
        public static final int notification_channel_name = 2131230728;
        public static final int short_name = 2131230729;
        public static final int shortcut_1_name = 2131230730;
        public static final int shortcut_1_short_name = 2131230731;
        public static final int shortcut_2_name = 2131230732;
        public static final int shortcut_2_short_name = 2131230733;
        public static final int shortcut_3_name = 2131230734;
        public static final int shortcut_3_short_name = 2131230735;
        public static final int shortcut_4_name = 2131230736;
        public static final int shortcut_4_short_name = 2131230737;
        public static final int site_settings_long_label = 2131230738;
        public static final int site_settings_short_label = 2131230739;
    }

    public static final class style {
        public static final int SplashTheme = 2131296256;
        public static final int WebappSplashScreenText = 2131296257;
        public static final int WebappSplashScreenTextTheme = 2131296258;
    }

    public static final class xml {
        public static final int shortcuts = 2131361792;
    }
}
